export const AUTH_VALIDATE_TOKEN = 'AUTH_VALIDATE_TOKEN'
export const AUTH_VALIDATE_TOKEN_SUCCESS = 'AUTH_VALIDATE_TOKEN_SUCCESS'
export const AUTH_VALIDATE_TOKEN_ERROR = 'AUTH_VALIDATE_TOKEN_ERROR'

export const AUTH_RENEW_TOKEN = 'AUTH_RENEW_TOKEN'
export const AUTH_RENEW_TOKEN_SUCCESS = 'AUTH_RENEW_TOKEN_SUCCESS'
export const AUTH_RENEW_TOKEN_ERROR = 'AUTH_RENEW_TOKEN_ERROR'

export const AUTH_FETCH_TOKEN = 'AUTH_FETCH_TOKEN'
export const AUTH_FETCH_TOKEN_SUCCESS = 'AUTH_FETCH_TOKEN_SUCCESS'
export const AUTH_FETCH_TOKEN_ERROR = 'AUTH_FETCH_TOKEN_ERROR'

export const AUTH_FETCH_USER = 'AUTH_FETCH_USER'
export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'


export const OPEN_CONTEXT_MENU = 'OPEN_CONTEXT_MENU'
export const CLOSE_CONTEXT_MENU = 'CLOSE_CONTEXT_MENU'


export const SEARCH = 'SEARCH'


export const INPUT_FIND_SUGGESTIONS = 'INPUT_FIND_SUGGESTIONS'
export const INPUT_CLEAR_SUGGESTIONS = 'INPUT_CLEAR_SUGGESTIONS'


export const ADD_MODAL = 'ADD_MODAL'
export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const UPDATE_MODAL = 'UPDATE_MODAL'
export const RESET_MODAL = 'RESET_MODAL'
export const REMOVE_MODAL = 'REMOVE_MODAL'


export const NEW_FORM = 'NEW_FORM'
export const ADD_FORM = 'ADD_FORM'
export const UPDATE_FORM = 'UPDATE_FORM'
export const UPADTE_FORM_META_ATTRIBUTE = 'UPADTE_FORM_META_ATTRIBUTE'
export const UPADTE_FORM_DATA_ATTRIBUTE = 'UPADTE_FORM_DATA_ATTRIBUTE'
export const RESET_FORM = 'RESET_FORM'
export const REMOVE_FORM = 'REMOVE_FORM'


export const NEW_REQUEST = 'NEW_REQUEST'
export const CHANGE_REQUEST_STATUS = 'CHANGE_REQUEST_STATUS'
export const ADD_RESPONSE_TO_REQUEST = 'ADD_RESPONSE_TO_REQUEST'
export const UPDATE_REQUEST = 'UPDATE_REQUEST'
export const DELETE_REQUEST = 'DELETE_REQUEST'
export const CLEAR_ALL_REQUESTS = 'CLEAR_ALL_REQUESTS'


export const FIND_ALL_CONFIGS = 'FIND_ALL_CONFIGS'
export const FIND_ONE_CONFIG = 'FIND_ONE_CONFIG'
export const CREATE_CONFIG = 'CREATE_CONFIG'
export const UPDATE_CONFIG = 'UPDATE_CONFIG'
export const API_DELETE_CONFIG = 'DELETE_CONFIG'


export const SEARCH_USERS = 'SEARCH_USERS'
export const FIND_ALL_USERS = 'FIND_ALL_USERS'
export const FIND_ONE_USER = 'FIND_ONE_USER'
export const CREATE_USER = 'CREATE_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const DELETE_USER = 'DELETE_USER'


export const SET_PREFERENCIAS = 'SET_PREFERENCIAS'


